name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for App to Start
        run: sleep 10

      - name: Curl HTML from Flask
        run: |
          mkdir -p build
          curl http://localhost:5001 > build/index.html

      - name: Stop Docker Containers
        run: docker compose down

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
